cd('C:\Users\sinnis\Desktop\fruit detection\10.14\1');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\2');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\3');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\4');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\5');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\6');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\7');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\8');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\9');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\10');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\11');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\12');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\13');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\14');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\15');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\16');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\17');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\18');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\19');
process_new;
cd('C:\Users\sinnis\Desktop\fruit detection\10.14\20');
process_new;